language: "pt-BR"

reviews:
  profile: "chill"
  auto_review:
    enabled: true
    drafts: false

  path_filters:
    - "!img/**" # Ignora a pasta de imagens para economizar processamento
    - "!*.png" # Ignora arquivos de imagem soltos
    - "!*.jpg"
    - "**/*" # Analisa todo o HTML, CSS e JavaScript

chat:
  enabled: true
